Code_source_logiciel/src/Entity/Mediation/MediationInterface.php
<?php

declare(strict_types=1);

namespace App\Entity\Mediation;

use App\Enum\ColorEnum;
use App\Enum\Mediation\PricingEnum;
use App\Enum\Mediation\SupervisionEnum;
use Doctrine\Common\Collections\Collection;
use Luna\CoreBundle\Model\Page\PageInterface as BasePageInterface;
use Luna\CoreBundle\Model\Trait\PositionnableTraitInterface;

interface MediationInterface extends BasePageInterface, PositionnableTraitInterface
{
    public function getColor(): ?ColorEnum;

    public function setColor(?ColorEnum $color): void;

    public function getAccessibility(): ?array;

    public function setAccessibility(?array $accessibility): void;

    public function getPricing(): ?PricingEnum;

    public function setPricing(?PricingEnum $pricing): void;

    public function getSupervision(): ?SupervisionEnum;

    public function setSupervision(?SupervisionEnum $supervision): void;

    public function getLevel(): ?array;

    public function setLevel(?array $level): void;

    public function getMonth(): ?array;

    public function setMonth(?array $month): void;

    public function getMediationProfessionals(): Collection;

    public function addMediationProfessional(MediationProfessional $mediationProfessional): void;

    public function removeMediationProfessional(MediationProfessional $mediationProfessional): void;

    public function getSubjects(): Collection;

    public function addSubject(MediationSubject $subject): void;

    public function removeSubject(MediationSubject $subject): void;

    public function getRelatedMediations(): Collection;

    public function addRelatedMediation(self $mediation): void;

    public function removeRelatedMediation(self $mediation): void;

    public function setPrice(?string $price): void;

    public function getPrice(): ?string;

    public function setAudience(?string $audience): void;

    public function getAudience(): ?string;

    public function setPeriod(?string $period): void;

    public function getPeriod(): ?string;

    public function setSchedule(?string $schedule): void;

    public function getSchedule(): ?string;

    public function setDuration(?string $duration): void;

    public function getDuration(): ?string;

    public function setLocation(?string $location): void;

    public function getLocation(): ?string;

    public function setPhone(?string $phone): void;

    public function getPhone(): ?string;
}

Code_source_logiciel/src/Entity/Mediation/MediationSubjectInterface.php
<?php

declare(strict_types=1);

namespace App\Entity\Mediation;

use Luna\CoreBundle\Model\Taxon\RichTaxonInterface;

interface MediationSubjectInterface extends RichTaxonInterface
{
}

Code_source_logiciel/src/Entity/Mediation/MediationSubjectTranslationInterface.php
<?php

declare(strict_types=1);

namespace App\Entity\Mediation;

use Luna\CoreBundle\Model\Taxon\RichTaxonTranslationInterface;

interface MediationSubjectTranslationInterface extends RichTaxonTranslationInterface
{
}

Code_source_logiciel/src/Entity/Menu/MenuItem.php
<?php

declare(strict_types=1);

namespace App\Entity\Menu;

use App\Enum\MenuItem\IconEnum;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use MonsieurBiz\SyliusMenuPlugin\Entity\MenuItem as BaseMenuItem;

#[ORM\Entity]
#[ORM\Table(name: 'monsieurbiz_menu_item')]
class MenuItem extends BaseMenuItem
{
    #[ORM\Column(name: 'icon', type: Types::STRING, enumType: IconEnum::class, nullable: true)]
    protected ?IconEnum $icon = null;

    #[ORM\Column(name: 'hide_label', type: Types::BOOLEAN, nullable: true)]
    protected ?bool $hideLabel = null;

    public function getIcon(): ?IconEnum
    {
        return $this->icon;
    }

    public function setIcon(?IconEnum $icon): void
    {
        $this->icon = $icon;
    }

    public function getHideLabel(): ?bool
    {
        return $this->hideLabel;
    }

    public function setHideLabel(?bool $hideLabel): void
    {
        $this->hideLabel = $hideLabel;
    }

    public function getDescription(): ?string
    {
        return $this->getTranslation()->getDescription();
    }
}

Code_source_logiciel/src/Form/Type/Block/MediationType.php
<?php

declare(strict_types=1);

namespace App\Form\Type\Block;

use App\Form\DataTransformer\MediationTransformer;
use App\Form\Type\Mediation\MediationAutocompleteChoiceType;
use Sylius\Component\Resource\Repository\RepositoryInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints as Assert;

class MediationType extends AbstractType
{
    public function __construct(private readonly RepositoryInterface $mediationRepository)
    {
    }

    public function getBlockPrefix(): string
    {
        return 'app_block_mediation';
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mediation', MediationAutocompleteChoiceType::class, [
                'required' => true,
                'multiple' => false,
                'resource' => 'app.mediation',
                'choice_name' => 'title',
                'choice_value' => 'id',
                'label' => 'app.ui.block.mediation.form.mediation.label',
                'constraints' => [
                    new Assert\NotBlank([]),
                ],
            ])
        ;

        $builder->get('mediation')->addModelTransformer(new MediationTransformer($this->mediationRepository));
    }
}

Code_source_logiciel/src/Form/Type/Block/MediationsType.php
<?php

declare(strict_types=1);

namespace App\Form\Type\Block;

use App\Form\DataTransformer\ProfessionalTransformer;
use Luna\CoreBundle\Form\Type\Block\ButtonType;
use MonsieurBiz\SyliusRichEditorPlugin\Form\Type\RichEditorType;
use Sylius\Component\Resource\Repository\RepositoryInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType as FormChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType as FormTextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints as Assert;

class MediationsType extends AbstractType
{
    public function __construct(private readonly RepositoryInterface $professionalRepository)
    {
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('professional', EntityType::class, [
                'class' => 'App\Entity\Professional\Professional',
                'required' => true,
                'multiple' => false,
                'choice_label' => 'title',
                'label' => 'app.ui.resource.page.form.professional.label',
                'help' => 'app.ui.resource.page.form.professional.help',
                'constraints' => [
                    new Assert\NotBlank([]),
                ],
            ])
            ->add('surtitle', FormTextType::class, [
                'required' => false,
                'label' => 'app.ui.block.mediations.form.surtitle.label',
                'help' => 'app.ui.block.mediations.form.surtitle.help',
            ])
            ->add('title', FormTextType::class, [
                'required' => true,
                'label' => 'app.ui.block.mediations.form.title.label',
                'help' => 'app.ui.block.mediations.form.title.help',
                'constraints' => [
                    new Assert\NotBlank([]),
                ],
            ])
            ->add('button', ButtonType::class, [
                'required' => false,
                'label' => 'app.ui.block.mediations.form.button.label',
                'help' => 'app.ui.block.mediations.form.button.help',
            ])
            ->add('formatting', FormChoiceType::class, [
                'required' => true,
                'label' => 'app.ui.block.mediations.form.formatting.label',
                'help' => 'app.ui.block.mediations.form.formatting.help',
                'choices' => [
                    'app.ui.block.mediations.form.formatting.choices.column' => 'column',
                    'app.ui.block.mediations.form.formatting.choices.line' => 'line',
                ],
            ])
            ->add('mediations', RichEditorType::class, [
                'required' => false,
                'label' => 'app.ui.block.mediations.form.mediations.label',
                'help' => 'app.ui.block.mediations.form.mediations.help',
                'tags' => ['-default', 'mediation'],
            ])
        ;

        $builder->get('professional')->addModelTransformer(new ProfessionalTransformer($this->professionalRepository));
    }
}

Code_source_logiciel/src/Form/Type/Mediation/MediationAutocompleteChoiceType.php
<?php

declare(strict_types=1);

namespace App\Form\Type\Mediation;

use Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\RouterInterface;

class MediationAutocompleteChoiceType extends AbstractType
{
    public function __construct(private readonly RouterInterface $router)
    {
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'resource' => 'app.mediation',
            'choice_name' => 'title',
            'choice_value' => 'id',
        ]);
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['remote_criteria_type'] = 'contains';
        $view->vars['remote_criteria_name'] = 'title';
        $view->vars['remote_url'] = $this->router->generate('app_admin_ajax_mediation_search_title');
        $view->vars['load_edit_url'] = $this->router->generate('app_admin_ajax_mediation_search_id');
    }

    public function getBlockPrefix(): string
    {
        return 'app_mediation_autocomplete_choice';
    }

    public function getParent(): string
    {
        return ResourceAutocompleteChoiceType::class;
    }
}

Code_source_logiciel/src/Form/Type/Mediation/MediationProfessionalType.php
<?php

declare(strict_types=1);

namespace App\Form\Type\Mediation;

use App\Entity\Mediation\MediationProfessional;
use App\Form\Type\Element\ProfessionalType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MediationProfessionalType extends ProfessionalType
{
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => MediationProfessional::class,
            'remove_alpha_field' => false,
        ]);
    }
}

Code_source_logiciel/src/Controller/Mediation/MediationController.php
<?php

declare(strict_types=1);

namespace App\Controller\Mediation;

use App\Entity\Mediation\Mediation;
use Luna\CoreBundle\Entity\Page\PageInterface;
use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Component\Resource\ResourceActions;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\Cache;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

class MediationController extends ResourceController
{
    #[Cache(public: true, maxage: 86400, mustRevalidate: true)]
    public function indexAction(Request $request): Response
    {
        return parent::indexAction($request);
    }

    #[Cache(public: true, maxage: 86400, mustRevalidate: true)]
    public function showAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::SHOW);
        /** @var Mediation $resource */
        $resource = $this->findOr404($configuration);

        $event = $this->eventDispatcher->dispatch(ResourceActions::SHOW, $configuration, $resource);
        $eventResponse = $event->getResponse();
        if (null !== $eventResponse) {
            return $eventResponse;
        }

        $underPagesService = $this->container->get('luna.under_pages.service');

        // Breadcrumb

        // Page parente de la ressource
        $page = $this->getDoctrine()->getManager()->getRepository(PageInterface::class)->findOneByCompositeSlug($request->getLocale(), $request->attributes->get('page_slug'));
        $pageSlug = $page->getCompositeSlug();
        $breadcrumb = $underPagesService->underPageBreadcrumbByPage($page);
        // Mediation en cours
        $label = $resource->getTitle();
        $href = $this->generateUrl('app_mediation_show', ['slug' => $resource->getSlug(), 'page_slug' => $pageSlug], UrlGeneratorInterface::ABSOLUTE_URL);
        $breadcrumb[] = ['label' => $label, 'href' => $href];

        // Utilisation du template show ou preview

        $template = '@SyliusShop/Mediation/show.html.twig';
        if ($request->attributes->get('preview')) {
            $showTemplate = $template;
            $template = '@LunaCore/Admin/Crud/preview.html.twig';
        }

        if ($configuration->isHtmlRequest()) {
            return $this->render($template, [
                'configuration' => $configuration,
                'metadata' => $this->metadata,
                'resource' => $resource,
                $this->metadata->getName() => $resource,
                'breadcrumb' => $breadcrumb,
                'page' => $page,
                'page_slug' => $pageSlug,
                'show_template' => $showTemplate ?? null,
            ]);
        }

        return $this->createRestView($configuration, $resource);
    }

    /**
     * @throws HttpException
     */
    public function moveupAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::UPDATE);
        /** @var Mediation $resource */
        $resource = $this->findOr404($configuration);

        // Récupération de l'entity manager
        $em = $this->getDoctrine()->getManager();

        $resource->setPosition($resource->getPosition() - 1);
        $em->persist($resource);
        $em->flush();

        return $this->redirectToRoute('app_admin_mediation_index');
    }

    /**
     * @throws HttpException
     */
    public function movedownAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::UPDATE);
        /** @var Mediation $resource */
        $resource = $this->findOr404($configuration);

        // Récupération de l'entity manager
        $em = $this->getDoctrine()->getManager();

        $resource->setPosition($resource->getPosition() + 1);
        $em->persist($resource);
        $em->flush();

        return $this->redirectToRoute('app_admin_mediation_index');
    }

    public function previewAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::UPDATE);
        /** @var Mediation $resource */
        $resource = $this->findOr404($configuration);

        return $this->forward('App\Controller\Mediation\MediationController::showAction', [
            'id' => $resource->getId(),
            'page_slug' => $request->attributes->get('page_slug'),
            '_route' => $request->attributes->get('_route'),
            '_under_pages_code' => $request->attributes->get('_under_pages_code'),
            'preview' => true,
        ]);
    }
}

Code_source_logiciel/src/Controller/Mediation/MediationSubjectController.php
<?php

declare(strict_types=1);

namespace App\Controller\Mediation;

use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Component\Resource\ResourceActions;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\Cache;

class MediationSubjectController extends ResourceController
{
    #[Cache(public: true, maxage: 86400, mustRevalidate: true)]
    public function showAction(Request $request): Response
    {
        return parent::showAction($request);
    }

    /**
     * @throws HttpException
     */
    public function moveupAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::UPDATE);
        /** @var MediationSubject $resource */
        $resource = $this->findOr404($configuration);

        // Récupération de l'entity manager
        $em = $this->getDoctrine()->getManager();

        $resource->setPosition($resource->getPosition() - 1);
        $em->persist($resource);
        $em->flush();

        return $this->redirectToRoute('app_admin_mediation_subject_index');
    }

    /**
     * @throws HttpException
     */
    public function movedownAction(Request $request): Response
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::UPDATE);
        /** @var MediationSubject $resource */
        $resource = $this->findOr404($configuration);

        // Récupération de l'entity manager
        $em = $this->getDoctrine()->getManager();

        $resource->setPosition($resource->getPosition() + 1);
        $em->persist($resource);
        $em->flush();

        return $this->redirectToRoute('app_admin_mediation_subject_index');
    }
}

Code_source_logiciel/templates/app/Admin/Mediation/Tab/_content.html.twig
<div class="ui tab" data-tab="content">
    <h3 class="ui top attached header">{{ 'luna.ui.menu.content'|trans }}</h3>

    <div class="ui attached segment">
        {{ form_errors(form) }}

        {% for locale, translationForm in form.translations %}
            <div data-locale="{{ locale }}">
                <div class="ui content{% if loop.first %} active{% endif %}">
                    <div class="transition hidden">{{ form_row(translationForm.blockable.init_ckeditor)}}</div>
                    {{ form_row(translationForm.blockable.blocks) }}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

Code_source_logiciel/templates/app/Admin/Mediation/Tab/_details.html.twig
{% import '@SyliusUi/Macro/flags.html.twig' as flags %}

<div class="ui active tab" data-tab="details">
    <h3 class="ui top attached header">{{ 'luna.ui.menu.details'|trans }}</h3>

    <div class="ui attached segment">
        {{ form_errors(form) }}

        <div class="ui segment">
            <div class="ui two column stackable grid">
                <div class="column">
                    <h4 class="ui header">{{ 'luna.ui.trait.toggleable.enabled.title'|trans }}</h4>
                    {{ form_row(form.toggleable.enabled) }}
                </div>
            </div>
        </div>

        <div class="ui one column stackable grid">
            <div class="column">

                <h4 class="ui dividing header">Types de professionnels</h4>

                <div class="ui two column stackable grid">
                    <div class="column">
                        {{ form_row(form.mediationProfessionals) }}
                    </div>
                    <div class="column">
                        {% for locale, translationForm in form.translations %}
                            <div data-locale="{{ locale }}">
                                <div class="ui small warning compact visible message">Pour éviter de la duplication de contenu dans les moteurs de recherche, il est nécessaire de renseigner ci-dessous, en tant qu'URL canonique, l'URL correspondant au type de professionel que vous souhaitez voir principalement associé à cette médiation dans les moteurs de recherche.</div>
                                {{ form_row(translationForm.seoable.canonicalUrl) }}
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <h4 class="ui dividing header">Classification</h4>

                <div class="ui two column stackable grid">
                    <div class="column">
                        {{ form_row(form.supervision) }}
                    </div>
                    <div class="column">
                        {{ form_row(form.accessibility) }}
                    </div>
                    <div class="column">
                        {{ form_row(form.subjects) }}
                    </div>
                    <div class="column">
                        {{ form_row(form.level) }}
                    </div>
                    <div class="column">
                        {{ form_row(form.month) }}
                    </div>

                </div>

                <h4 class="ui dividing header">{{ 'luna.ui.resource.page.form.page_info'|trans }}</h4>

                {{ form_row(form.color) }}

                {% for locale, translationForm in form.translations %}
                    <div data-locale="{{ locale }}">

                        {{ form_row(translationForm.titleable.title) }}

                        {{ form_row(translationForm.titleable.slug) }}

                        {{ form_row(translationForm.describable.description) }}

                        {{ form_row(translationForm.period) }}

                        {{ form_row(translationForm.schedule) }}

                        {{ form_row(translationForm.duration) }}

                        {{ form_row(form.pricing) }}

                        {{ form_row(translationForm.price) }}

                        {{ form_row(translationForm.location) }}

                        {{ form_row(translationForm.audience) }}

                        {{ form_row(translationForm.phone) }}

                        {{ form_row(form.relatedMediations) }}

                        {{ form_row(translationForm.mainImage) }}

                    </div>
                {% endfor %}


            </div>
        </div>

    </div>
</div>

Code_source_logiciel/templates/app/Admin/Mediation/Tab/_seo.html.twig
<div class="ui tab" data-tab="seo">
    <h3 class="ui top attached header">{{ 'luna.ui.menu.seo'|trans }}</h3>

    <div class="ui attached segment">
        {{ form_errors(form) }}

        <h4 class="ui dividing header">{{ 'luna.ui.trait.seoable.seo_header'|trans }}</h4>

        <div class="ui segment">
            {{ form_row(form.seoable.noIndex) }}
            {% for locale, translationForm in form.translations %}
                <div data-locale="{{ locale }}">
                    <div class="ui content{% if loop.first %} active{% endif %}">
                        {{ form_row(translationForm.seoable.metaTitle) }}
                        {{ form_row(translationForm.seoable.metaDescription) }}
                    </div>
                </div>
            {% endfor %}
        </div>

        <h4 class="ui dividing header">{{ 'luna.ui.trait.seoable.open_graph_header'|trans }}</h4>

        <div class="ui segment">
            {% for locale, translationForm in form.translations %}
                <div data-locale="{{ locale }}">
                    <div class="ui content{% if loop.first %} active{% endif %}">
                        {{ form_row(translationForm.seoable.openGraphTitle) }}
                        {{ form_row(translationForm.seoable.openGraphDescription) }}
                        {{ form_row(translationForm.seoable.openGraphImage) }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>